### ISSUE TITLE
[Add BlockList] https://phishing.army/

### ISSUE THREAD

**Issue by Darioits** [drego85/PhishingArmyCore#3]
Can we add this block list to https://my.nextdns.io/
thank you in advance

**Comment by drego85** [comment]
[Phishing Army](https://phishing.army/) was one of the first lists integrated into NextDNS, within the Threat Intelligence feed. You can activate it in the 'Security' tab.

[Here a list.](https://github.com/nextdns/metadata/blob/01087986958fd31713bdfa64201d2f8b0ddca84a/security/threat-intelligence-feeds.json)

**Comment by Darioits** [comment]
oh thank you very much, I already activate it!
